### ISSUE TITLE
Interface vs Pure abstract class in the API

### ISSUE THREAD

**Issue by bogdandrutu** [bogdandrutu/openconsensus#19]
* Pros for Abstract
  * Keep backwards compatibility between the API and implementation.
* Cons for Abstract
  * No support for multiple inheritance.
  * Interfaces may be consider cleaner for API than abstract classes.

**Comment by yurishkuro** [comment]
I think a related question here is API vs. SPI. Currently Tracer abstract class has things like withRunnable(), which are simply util methods that normally don't require vendors overriding them.

Regarding backwards compatibility of the abstract class, it can still be achieved by providing both the interface (the basic API block) and an abstract implementation that vendors are encouraged to extend in order to benefit from default / util methods (but again, default/util methods on the same type are a bit of a design smell, hinting at inadequate API/SPI separation).

**Comment by bogdandrutu** [comment]
Based on my understanding users instrumentation code should not depend on SPI (SPI is intended to be used by the service provider (vendor) to implement the API). See https://en.wikipedia.org/wiki/Service_provider_interface

The abstract implementation that vendors should extend seems to be the SPI.

**Comment by tedsuo** [comment]
For now, we are using Abstract implementation.

@carlosalberto will get feedback from implementors as to whether this is a workable choice..

**Comment by tedsuo** [comment]
Interface PRO: interfaces allow implementations to control their class hierarchy better. For example, an implementation that implements both `Span` and `SpanBuilder`. 

We can still offer an Abstract class which implements each interface, for convenience.

TODO: switch to interfaces in Java.

**Comment by carlosalberto** [comment]
Shall we switch to interfaces then?
